### ISSUE TITLE
where to put the roms?

### ISSUE THREAD

**Issue by c0deisme** [Good-Old-Downloads/rg#1]
maybe i have overseen.. but there is no rom folder and the scripts seem to scan a folder that is only ever mentioned as a variable..
so.. how to set the rom folder or what folder would it be?

**Comment by Good-Old-Downloads** [comment]
Why would there be a rom folder?

**Comment by c0deisme** [comment]
isnt it mentioned in the admin interface and the scanning scripts?

or how do you add roms to the database?

**Comment by t94xr** [comment]
I believe they were stored offsite?

**Comment by c0deisme** [comment]
they were, but the scripts mention scanning roms, so is in the admin interface

**Comment by Good-Old-Downloads** [comment]
Adding a single ROM:
```shell
curl -X POST https://rg.dev/api/rom/add  -F 'name=Mario Kart 64 (USA)' -F 'console=nintendo-64' -F 'dirinfoid=11' -H 'X-Api-Key: key-from-config'
```

If you have a batch list, use [parse_internal.php](/Good-Old-Downloads/rg/blob/master/scripts/parse_internal.php) via the command line:
```shell
php parse_internal.php n64.txt nintendo-64 11
```

You may want to check out the [directory_info](/Good-Old-Downloads/rg/blob/master/db.sql#L235) and [console](/Good-Old-Downloads/rg/blob/master/db.sql#L19) tables to see what params you want to pass in.

**Comment by c0deisme** [comment]
thanks!
